### ISSUE TITLE
Wexpect issue while trying to use ssh from windows 7

### ISSUE THREAD

**Issue by teddyjoe** [jasonrgd/WExpectForPython3#1]
I am very much new to python and wexpect. I am trying to import and use python WExpect module as is to connect from my windows machine to linux server. while doing it , I am getting a following error.
ExceptionPexpect :The command was not found or was not executable: ssh root@192.00.00.00.
basically I want to connect to that server ip using wexpect and the start interacting with it .
Can anyone please help me on it.
I running my python script from my windows environment(CMD)

Actual error message is below
Traceback (most recent call last):
File "D:\Toyota-Brazil\WorkProducts\pytomy\frameui.py", line 5, in 
cmd = spawn('ssh root@192.00.00.00')
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 144, in spawn
return spawn_windows(command, args, timeout, maxread, searchwindowsize, logfile, cwd, env)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1411, in init
self._spawn (command, args)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1456, in _spawn
raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: ssh root@192.00.00.00.

Can anyone help me one this?

**Comment by jasonrgd** [comment]
Unfortunately I'm no longer maintaining this. I'm happy for it to be forked.
